version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Papamen123!
      MYSQL_DATABASE: games
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Papamen123!
      DB_NAME: games
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  db-data: